version: "3.1"
services:
  database:
    image: "postgres:15"
    environment:
      POSTGRES_USER: dbadm
      POSTGRES_PASSWORD: JS2299Z@dAH$
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
